services:
  pmm-server:
    image: percona/pmm-server:3
    container_name: pmm-server
    restart: always
    ports:
      - "443:8443"
    volumes:
      - pmm-data:/srv
    networks:
      - pmm-network

volumes:
  pmm-data:
    name: pmm-data

networks:
  pmm-network:
    name: pmm-network
    driver: bridge
